module.exports = {
  docs: [
    "overview",
    "installation",
    "structure",
    {
      Guides: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
    },
    {
      Changelog: [
        {
          type: "autogenerated",
          dirName: "changelog",
        },
      ],
    },
  ],
  api: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};
